name: task_flow_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  im_stepper: ^1.0.1+1
  multi_select_flutter: ^4.1.3
  multi_dropdown: ^2.1.4
  logger: ^2.0.2+1
  image_picker: ^1.0.7
  dio: ^5.4.1
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InriaSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/InriaSans-Light.ttf
          weight: 300
