name: task_flow_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  go_router: ^13.2.0
  im_stepper: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InriaSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/InriaSans-Light.ttf
          weight: 300
